# Generated by Django 5.2.8 on 2025-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(max_length=10),
        ),
    ]
